version: '3.1'

networks:
  web-network:
    driver: bridge

services:

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    networks:
      - web-network
    volumes:
      - ./vue/dist:/usr/share/nginx/html/:rw
    ports:
      - "8085:80"

  php:
    container_name: php
    build: .
    working_dir: /app
    restart: always
    networks:
      - web-network
    volumes:
      - ./:/app:rw
    environment:
      BYBIT_HOST: ***
      BYBIT_APIKEY: ***
      BYBIT_SECRET: ***
      SYMBOL: BTCUSDT,ETHUSDT,LTCUSDT,MNTUSDT,XRPUSDT,ARBUSDT,APTUSDT
      WEBSOCKET_PORT: 8001
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - "8001:8001"

  node:
    container_name: node
    image: node
    working_dir: /app
    volumes:
      - ./vue:/app:rw
    command: bash -c "
      npm install
      && npm run build
      "